# Generated by Django 2.1.3 on 2018-11-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('humedad', models.CharField(max_length=100)),
                ('temperatura', models.CharField(max_length=100)),
                ('rayos_v', models.CharField(max_length=100)),
                ('sensor_lluvia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
