# Generated by Django 2.1.3 on 2018-11-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
