# Generated by Django 2.1.3 on 2018-11-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181107_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='updated_at',
        ),
    ]
